[project]
name = "dhagam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "haystack-ai>=2.14.1",
    "ipykernel>=6.29.5",
    "trafilatura>=2.0.0",
]
